ProjectWEB/ProjectWEB/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ProjectWEB/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('best-questions', views.best_questions, name='best-questions'),
    path('new-questions', views.new_questions, name='new-questions'),
    path('question/<str:id>', views.question, name='question'),
    path('ask', views.ask, name='ask'),
    path('settings', views.settings, name='settings'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('tag/<str:name>', views.tag, name='tag'),
    path('logout', views.user_logout, name='user_logout'),
    path('admin/', admin.site.urls),
]

app/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class QuestionManager(models.Manager):
    pass


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    nickname = models.CharField(max_length=255, null=True)
    profile_image = models.ImageField(default='messi.jpg')


class Question(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=1000)
    tags = models.ManyToManyField('Tag')
    likes = models.PositiveIntegerField(default=0)
    # likes = models.ManyToManyField(Profile, related_name='liked_questions')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='questions', null=True)
    date_written = models.DateField(null=True)
    objects = QuestionManager()


class Answer(models.Model):
    parent_question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    content = models.CharField(max_length=1000)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    # likes = models.PositiveIntegerField(default=0)
    date_written = models.DateField(null=True)
    likes = models.ManyToManyField(User, related_name='liked_answers')


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)

app/views.py
from django.shortcuts import render, redirect
from django.db.models import Count
from django.core.paginator import Paginator
from .models import Question, Tag, Profile
from django.contrib.auth.models import User
from django.contrib.auth import login as user_login, authenticate, logout
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404, HttpResponse


def paginate(objects, request, per_page):
    paginator = Paginator(objects, per_page)
    page = request.GET.get('page', 1)
    try:
        page_items = paginator.page(page).object_list
    except PageNotAnInteger:
        page_items = paginator.page(1).object_list
    except EmptyPage:
        raise Http404("Страница не существует")
    return page_items


def get_tag(Tag):
    return Tag.objects.annotate(num_questions=Count('question')).order_by('-num_questions')[:10]


tags = get_tag(Tag=Tag)


# Create your views here.
def index(request):
    questions = Question.objects.all()
    best_users = Profile.objects.annotate(total_likes=Count('user__questions__likes') +
                                                      Count('user__answer__likes')).order_by(
        'total_likes')[:10]
    return render(request, 'index.html',
                  {'questions': paginate(questions, request, per_page=20), 'tags': tags,
                   'best_users': best_users})


def best_questions(request):
    best_users = Profile.objects.annotate(total_likes=Count('user__questions__likes') +
                                                      Count('user__answer__likes')).order_by(
        'total_likes')[:10]
    best_questions = Question.objects.all().exclude(likes=None).order_by("-likes")
    return render(request, 'index.html',
                  {'questions': paginate(best_questions, request, per_page=20), 'tags': tags,
                   'best_users': best_users})


def new_questions(request):
    best_users = Profile.objects.annotate(total_likes=Count('user__questions__likes') +
                                                      Count('user__answer__likes')).order_by(
        'total_likes')[:10]
    new_questions = Question.objects.all().exclude(date_written=None).order_by("-date_written")
    return render(request, 'index.html',
                  {'questions': paginate(new_questions, request, per_page=20), 'tags': tags,
                   'best_users': best_users})


def question(request, id):
    best_users = Profile.objects.annotate(total_likes=Count('user__questions__likes') +
                                                      Count('user__answer__likes')).order_by(
        'total_likes')[:10]
    question_object = Question.objects.get(id=id)
    answers = question_object.answer_set.order_by("-date_written", "-likes")
    return render(request, 'question.html',
                  {'tags': tags, 'question': question_object, 'best_users': best_users, 'answers': answers})


def tag(request, name):
    tag_object = Tag.objects.get(name=name)
    best_users = Profile.objects.annotate(total_likes=Count('user__questions__likes') +
                                                      Count('user__answer__likes')).order_by(
        'total_likes')[:10]
    return render(request, 'tag.html',
                  {'tag': tag_object, 'tags': tags, 'best_users': best_users})


def ask(request):
    best_users = Profile.objects.annotate(total_likes=Count('user__questions__likes') +
                                                      Count('user__answer__likes')).order_by(
        'total_likes')[:10]
    return render(request, 'ask.html', {'tags': tags, 'best_users': best_users})


def settings(request):
    best_users = Profile.objects.annotate(total_likes=Count('user__questions__likes') +
                                                      Count('user__answer__likes')).order_by(
        'total_likes')[:10]
    return render(request, 'settings.html', {'tags': tags, 'best_users': best_users})


def login(request):
    if request.method == 'POST':
        login = request.POST.get("login")
        password = request.POST.get("password")
        user = authenticate(username=login, password=password)

        if user is not None:
            user_login(request, user)
            return redirect('index')

        else:
            return HttpResponse(status=403)

    else:
        best_users = Profile.objects.annotate(total_likes=Count('user__questions__likes') +
            Count('user__answer__likes')).order_by('total_likes')[:10]
        return render(request, 'login.html', {'tags': tags, 'best_users': best_users})


def user_logout(request):
    logout(request)
    return redirect('index')


def register(request):
    if request.method == 'POST':
        login = request.POST['login']
        email = request.POST['email']
        nickname = request.POST['nickname']
        pass1 = request.POST['password']
        pass2 = request.POST['password2']
        # avatar = request.POST['avatar']

        if pass2 != pass1:
            return HttpResponse(status=400)

        else:
            try:
                new_user = User.objects.create_user(username=login, email=email, password=pass1)
                new_profile = Profile.objects.create(nickname=nickname, user=new_user)
                new_user.save()
                new_profile.save()
                user_login(request, new_user)
                return redirect('index')

            except:
                return HttpResponse(status=400)

    else:
        best_users = Profile.objects.annotate(total_likes=Count('user__questions__likes') +
                                                          Count('user__answer__likes')).order_by(
            'total_likes')[:10]
        return render(request, 'register.html', {'tags': tags, 'best_users': best_users})


def like_question(request, question_id, profile_id):
    profile = Profile.objects.get(id=profile_id)
    question = Question.objects.get(id=question_id)
    question.likes.add(profile)
    return HttpResponse(status=200)

templates/ask.html
{% extends 'layouts/base.html' %}

{% block content %}

    <h3>Задайте свой вопрос</h3>
    <form>
        <div class="mb-3">
            <label for="questionDescription" class="form-label">Кратко опишите проблему</label>
            <input type="text" class="form-control" id="questionDescription">
        </div>
        <div class="mb-3">
            <label>Опишите проблему как можно подробнее
                <textarea class="form-control" rows="10" cols="100"></textarea>
            </label>
        </div>
        <div class="mb-3">
            <label for="questionTags" class="form-label">Добавьте теги через запятую</label>
            <input type="text" class="form-control" id="questionTags">
        </div>
        <button type="submit" class="btn btn-primary">Спросить</button>
    </form>


{% endblock %}

templates/components/answer-item.html
{% load static %}

<div class="row question">
    <div class="col-3">
        <img src="{% static '/img/among_us.jpg' %}" alt="" class="question-image">
    </div>
    <div class="col-9">
        <div class="question-text">{{ answer.content }}</div>
    </div>
    <div class="col-3">
         <div class="like-container">
                <div class="comment-votes btn-group btn-group" role="group"
                     aria-label="Comment votes">
                    <span class="btn btn-secondary px-2 py-0 active"><span
                            class="badge badge-secondary">{{ answer.likes }}</span></span>
                    <button type="button" class="btn btn-outline-secondary px-1 py-0 shadow-none">&#8593;</button>
                    <button type="button" class="btn btn-outline-secondary px-1 py-0 shadow-none">&#8595;</button>
                </div>
            </div>
    </div>
        <div class="col-9">
            <div>
                <input type="checkbox" style="margin-top: 30px"> Правильный ответ
            </div>
        </div>
    </div>

templates/components/question-item.html
{% load static %}


<div class="row question">
    <div class="col-3">
        <img src="{% static '/img/messi.jpg' %}" alt="" class="question-image">
    </div>
    <div class="col-9">
        <div class="question-title">
            <a href="/question/{{ question.id }}">{{ question.title }}</a>
        </div>
        <div class="question-text">{{ question.content }}</div>
    </div>
    <div class="col-3">
        <div>
            <div class="like-container">
                <div class="comment-votes btn-group btn-group" role="group"
                     aria-label="Comment votes">
                    <span class="btn btn-secondary px-2 py-0 active"><span
                            class="badge badge-secondary">{{ question.likes }}</span></span>
                    <button type="button" class="btn btn-outline-secondary px-1 py-0 shadow-none">
                        &#8593;
                    </button>
                    <button type="button" class="btn btn-outline-secondary px-1 py-0 shadow-none">
                        &#8595;
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="question-answers"
             style="margin-top: 30px"
        ><a href="/question/{{ question.id }}">Ответы ({{ question.answer_set.all.count }})</a>
        </div>
    </div>

    <div class="col-7">
        <div class="question-tags"
             style="margin-top: 30px">
            <div class="tags"
                 style="border: none; max-width: 280px; border-radius: 15px; padding:0px">
                {% for tag in question.tags.all %}
                <span class="badge bg-primary"><a href="/tag/{{ tag.name }}"
                                                  style="text-decoration: none;
                                                  color: white">{{ tag.name }}</a></span>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

templates/components/user_status.html
{% if user.is_authenticated %}
    {% load static %}
    <li class="nav-item">
        <a class="navbar-brand" href="{% url 'settings' %}">
            <img src="{% static '/img/avatar.webp' %}" alt="" width="40"
                 height="40">
        </a>
    </li>
    <li class="nav-item">
        <h1 class="username">{{ request.user.username }}</h1>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'settings' %}">Настройки</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" id="login_btn" aria-current="page" href="{% url 'user_logout' %}">Выйти</a>
    </li>
{% else %}
    <li class="nav-item">
        <a class="nav-link active" id="login_btn" aria-current="page" href="{% url 'login' %}">Войти</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'register' %}">Регистрация</a>
    </li>
{% endif %}

templates/index.html
{% extends 'layouts/base.html' %}

{% block content %}

    <div class="row" style="margin-top: 10px">
        <div class="col-4">
            <h3><a href="{% url 'new-questions' %}">Новые вопросы</a></h3>
        </div>
        <div class="col-8">
            <h3><a href="{% url 'best-questions' %}">Популярные вопросы</a></h3>
        </div>
    </div>

    {% for question in questions %}

        {% include 'components/question-item.html' %}

    {% endfor %}

    <nav class="mt-3 d-flex justify-content-center">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>

{% endblock %}

templates/layouts/base.html
{% load static %}

<!doctype html>

<html lang="en" class="h-100">
<head>
    <title>VK вопросы</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static '/css/bootstrap.css' %}" rel="stylesheet">
    <meta charset="UTF-8">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
            display: block !important;
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static '/css/main.css' %}" rel="stylesheet">
</head>
<body class="d-flex flex-column h-100">

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">VK Вопросы</a>
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <form class="d-flex flex-fill me-5" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search"
                           aria-label="Search">
                    <button class="btn btn-light" type="submit">Поиск</button>
                </form>
                <div class="ask-button" id="ask-button">
                    <a class="btn btn-info"
                       href="{% url 'ask' %}" style="margin-right: 40px" role="button">Спросить</a>
                </div>
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                    {% include 'components/user_status.html' %}
                </ul>


            </div>
        </div>
    </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">
    <div class="container">
        <div class="row">
            <div class="col-8">
                {% block content %}
                {% endblock %}
            </div>
            <div class="col-4">
                <div class="row" style="margin-top: 10px;margin-left: 120px">
                    <h3>Популярные теги</h3>
                    <div class="tags"
                         style="border: 1px solid grey; max-width: 280px; border-radius: 15px; padding: 10px;">
                        {% for tag in tags %}
                            <span class="badge bg-primary"><a href="{% url 'tag' name=tag.name %}"
                                                              style="text-decoration: none;
                                                          color: white">{{ tag.name }}</a></span>
                        {% endfor %}
                    </div>
                    <br/>
                    <div class="row" style="margin-top: 25px">
                        <h3>Активные пользователи</h3>
                        <ul class="list-group list-group-flush"
                            style="border: 1px solid grey; max-width: 280px; border-radius: 15px; padding: 10px;">
                            {% for user in best_users %}
                                <li class="list-group-item">{{ user.user.username }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>


<script src="{% static '/js/bootstrap.js' %}"></script>
</body>
</html>

templates/login.html
{% extends 'layouts/base.html' %}

{% block content %}
    <h3 xmlns="http://www.w3.org/1999/html">Войти</h3>

    <form method="post" action="{% url 'login' %}" enctype="multipart/form-data" class="login_form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="login" class="form-label">Логин</label>
            <input type="text" class="form-control" id="login" name="login"
                   aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Пароль</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>
        <div class="mb-3 form-check">
            <input type="checkbox" class="form-check-input" id="exampleCheck1">
            <label class="form-check-label" for="exampleCheck1">Запомнить меня</label>
        </div>
        <button type="submit" class="btn btn-primary">Войти</button>
    </form>

    <div class="CreateNewAccount">
        <h1></h1>
        <a href="{% url 'register' %}">Создать новый аккаунт</a>
    </div>

{% endblock %}

templates/question.html
{% extends 'layouts/base.html' %}

{% include 'components/question-item.html' %}

{% block content %}

    {% include 'components/question-item.html' %}

    <section class="answers mt-5">

        <h2>Ответы</h2>

        {% for answer in answers %}
            {% include 'components/answer-item.html' %}
        {% endfor %}

        <nav class="mt-3 d-flex justify-content-center">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
        </nav>


        <div class="row">
            <form class="col-12 border p-3">
                <div class="mb-3">
                    <label class="form-label w-100">
                        заголовок ответа
                        <input type="text" class="form-control">
                    </label>
                </div>
                <div class="mb-3">
                    <label class="form-label w-100">
                        ответ на вопрос
                        <textarea class="form-control"></textarea>
                    </label>
                </div>
                <button type="submit" class="btn btn-primary">Ответить</button>
            </form>
        </div>
    </section>

{% endblock %}

templates/register.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="col-9 my-4">
        <div class="d-flex justify-content-start align-items-center">
            <h2>Регистрация</h2>
        </div>
{#        <div class="d-flex justify-content-start align-items-center">#}
{#            <p class="text-danger">Извините, этот email адрес уже используется</p>#}
{#        </div>#}

        <div class="container p-3 my-3">

            <form method="post" action="{% url 'register' %}" enctype="multipart/form-data" class="login_form">
                {% csrf_token %}
                <div class="row align-items-center">

                    <div class="col-2 px-0">
                        <label for="loginName" class="text-body fs-5 my-0">Логин</label>
                    </div>

                    <div class="col-10">
                        <div class="form-group">
                            <input type="text" name="login" class="form-control"
                                   placeholder="Введите логин"/>
                        </div>
                    </div>
                </div>

                <div class="row my-4">

                    <div class="col-2 px-0">
                        <label for="email" class="text-body fs-5">Email</label>
                    </div>

                    <div class="col-10">
                        <input name="email" type="email" class="form-control"
                               placeholder="Ваш email"/>
                    </div>
                </div>

                <div class="row my-4">

                    <div class="col-2 px-0">
                        <label for="nickname" class="text-body fs-5">Никнейм</label>
                    </div>

                    <div class="col-10">
                        <input name="nickname" type="text" class="form-control"
                               placeholder="Введите свой никнейм"/>
                    </div>
                </div>

                <div class="row my-4">

                    <div class="col-2 px-0">
                        <label for="password" class="text-body fs-5">Пароль</label>
                    </div>

                    <div class="col-10">
                        <input name="password" type="password" class="form-control"
                               placeholder="Введите пароль"/>
                    </div>
                </div>

                <div class="row my-4">

                    <div class="col-2 px-0">
                        <label for="password2" class="text-body fs-5">Повторите пароль</label>
                    </div>

                    <div class="col-10">
                        <input name="password2" type="password" class="form-control"
                               placeholder="Введите пароль ещё раз"/>
                    </div>
                </div>

{#                <div class="row my-4">#}
{##}
{#                    <div class="col-2 px-0">#}
{#                        <label for="avatar" class="text-body fs-5">Фото профиля</label>#}
{#                    </div>#}
{##}
{#                    <div class="col-10">#}
{#                        <input type="file" class="form-control text-secondary" name="avatar"#}
{#                               placeholder="Выберите фото"/>#}
{#                    </div>#}
{#                </div>#}

                <div class="row align-items-center">

                    <div class="col-2 px-0">
                        <p></p>
                    </div>

                    <div class="col-10">
                        <button type="submit" class="btn btn-primary px-5">Регистрация</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/settings.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="col-9 my-4">

        <div class="d-flex justify-content-start align-items-center">
            <h2 class="text-body">Настройки: </h2>
            <h2 class="text-body mx-3">Username</h2>
        </div>

        <div class="d-flex justify-content-start align-items-center">
            <p class="text-danger">Неправильный формат фото!</p>
        </div>

        <div class="container p-3 my-3">
            <div class="row align-items-center">

                <div class="col-2 px-0">
                    <label for="loginName" class="text-body fs-5 my-0">Логин</label>
                </div>

                <div class="col-10">
                    <div class="form-group">
                        <input type="email" id="loginName" name="loginName" class="form-control"
                               placeholder="Введите логин"/>
                    </div>
                </div>
            </div>

            <div class="row my-4">

                <div class="col-2 px-0">
                    <label for="email" class="text-body fs-5">Email</label>
                </div>

                <div class="col-10">
                    <input id="email" type="email" class="form-control"
                           placeholder="Введите Ваш email"/>
                </div>
            </div>

            <div class="row my-4">

                <div class="col-2 px-0">
                    <label for="nickname" class="text-body fs-5">Никнейм</label>
                </div>

                <div class="col-10">
                    <input id="nickname" type="text" class="form-control"
                           placeholder="Введите никнейм"/>
                </div>
            </div>

            <div class="row my-4">

                <div class="col-2 px-0">
                    <label for="avatar" class="text-body fs-5">Выберите фото профиля</label>
                </div>

                <div class="col-10">
                    <img src="https://klike.net/uploads/posts/2023-01/1674365337_3-31.jpg"
                         class="rounded-3" style="width: 100px;" alt="Avatar"/>
                </div>
            </div>

            <div class="row align-items-center">

                <div class="col-2 px-0">
                    <p></p>
                </div>

                <div class="col-10">
                    <input type="file" class="form-control text-secondary" id="avatar"
                           placeholder="Выберите фото профиля"/>
                </div>
            </div>

            <div class="row align-items-center">

                <div class="col-2 px-0">
                    <p></p>
                </div>

                <div class="col-10">
                    <button type="button" class="btn btn-primary px-5 my-4">Сохранить</button>
                </div>
            </div>
        </div>

    </div>
{% endblock content %}

templates/tag.html
{% extends 'layouts/base.html' %}

{% block content %}

    <h3>Вопросы с тегом {{ tag.name }}</h3>

    {% for question in tag.question_set.all %}
        {% include 'components/question-item.html' %}
    {% endfor %}

    <nav class="mt-3 d-flex justify-content-center">
        <ul class="pagination">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>

{% endblock %}